### ISSUE TITLE
Get DID Doc Json

### ISSUE THREAD

**Issue by 2byrds** [roots-id/wal-cli#15]
I need a wal-lib method like getDidDoc that takes a prism DID (string) and returns a non-prism api JSON string

RootsWaallet wants to resolve DID docs from other users DIDs.

**Comment by Essbante** [comment]
@2byrds use:
fun getDidDocumentJson(didAlias: String): String {
    return getDidDocument(didAlias).didData.toProto().encodeToJsonString()
}

new features will be added to develop branch (including this one)
